### ISSUE TITLE
No segmentation masks in json file

### ISSUE THREAD

**Issue by samuellukudu** [nahitorres/AerialWaste#1]
I have been looking through the json file, but I was unable to find segmentation masks.

**Comment by nahitorres** [comment]
Hello Samuel!

You need to go to [Zenodo](https://zenodo.org/records/7991872), and download the testing.json file, there you can see the attribute 'annotations' with all the segmentations for the testing split (as specified in the [paper](https://www.nature.com/articles/s41597-023-01976-9)):

![image](https://github.com/nahitorres/AerialWaste/assets/62382874/07de3f30-22d3-4203-b563-dc07c69adc8c)

There are two notebooks that might help you visulize/process the annotations:

- Visualize them with help of ODIN too (as per readme) https://github.com/nahitorres/AerialWaste/blob/main/Visualizer-IS.ipynb
- Transform them into bounding boxes: https://github.com/nahitorres/AerialWaste/blob/main/compute_bbox_from_segmentation.ipynb


Best!

**Comment by samuellukudu** [comment]
Oh thanks. I only viewed the training.json file
